# Generated by Django 5.2.10 on 2026-02-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('tayyorlanmoqda', 'Tayyorlanmoqda'), ('yetkazildi', 'Yetkazildi'), ('bekor_qilindi', 'Bekor qilindi')], default='tayyorlanmoqda', max_length=20),
        ),
    ]
