# Generated by Django 5.2.10 on 2026-01-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='images/clients/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
